import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {resolve,join,sep} from 'node:path';
import {createHmac} from 'node:crypto';
import {Store} from '../server/store.mjs';
import {createConversation} from '../server/domain/tripWorkspace.mjs';
import {saveBookingDetails,createBookingReview,submitBookingOperation,runBookingOperation,approvedCheckoutUrl} from '../server/shopping/booking.mjs';
import {DuffelBookingAdapter} from '../server/shopping/duffelBooking.mjs';
import {verifyDuffelWebhook,receiveDuffelWebhook} from '../server/shopping/webhooks.mjs';
function fixture(t){
 mkdirSync('tmp',{recursive:true});const dir=mkdtempSync(join(resolve('tmp'),'booking-flow-')),store=new Store({directory:dir,production:false});
 t.after(()=>{store.close();assert.ok(resolve(dir).startsWith(resolve('tmp')+sep));rmSync(dir,{recursive:true,force:true});});
 const user=store.createGuest(),other=store.createGuest(),w=createConversation(store,user.id);
 const search=store.put(user.id,'shopping-search',{offers:[{id:'off_fixture',passengerMap:{pas_fixture:'adult-1'}}],request:{},state:'complete'});
 const set=store.put(user.id,'candidate-set',{conversationId:w.conversation.id,searchId:search.id});
 const draft=store.put(user.id,'trip-draft',{...w.draft,constraints:{...w.draft.constraints,mode:'flights',departure:new Date(Date.now()+86400000*7).toISOString(),passengers:[{id:'adult-1',type:'adult',personal:0,cabin:0,checked:0}]},selected:{setId:set.id,optionId:'option-fixture',flight:{id:'off_fixture'},journey:{id:'flight-fixture'}}},{id:w.draft.id,expectedVersion:w.draft.version});
 const data={passengers:[{id:'adult-1',givenName:'Test',familyName:'Traveler',bornOn:'1990-01-01',title:'ms',gender:'f',email:'fixture@example.invalid',phone:'+12025550123'}],services:[],paymentMethod:'card',cardId:'tcd_fixture'};
 const details=saveBookingDetails(store,user.id,w.conversation.id,{draftVersion:draft.version,details:data});
 const calls={quote:0,submit:0,reconcile:0};const state={amount:12345,fail:false,issued:true,decline:false};
 const quote=()=>({id:'off_fixture',expiresAt:Date.now()+240000,charge:{amount:state.amount,currency:'USD',scale:2},refund:null,terms:'Fixture fare and cancellation terms',itinerary:{services:['fixture-service'],passengers:['adult-1']},complete:true,supplier:'fixture',live:false,paymentAuthenticationRequired:true,supplierPayload:{offerId:'off_fixture'}});
 const outcome=()=>({authoritative:true,supplier:'fixture',live:false,reference:'ord_fixture',paymentState:state.decline?'declined':'captured',ticketState:state.issued?'issued':'not-issued',documents:state.issued?[{type:'electronic_ticket',reference:'fixture-document'}]:[]});
 const adapter={name:'fixture',live:false,authorized:true,capabilities:{book:true,cancel:true,exchange:true,refund:true},quote:async()=>{calls.quote++;return quote();},refreshQuote:async()=>quote(),submit:async()=>{calls.submit++;if(state.fail)throw Error('Uncertain connection');return outcome();},reconcile:async()=>{calls.reconcile++;return outcome();}};
 const review=()=>createBookingReview(store,user.id,{kind:'book',detailsId:details.id},adapter);
 const submit=r=>submitBookingOperation(store,user.id,{reviewId:r.id,key:r.id,confirmed:true,confirmationToken:r.confirmationToken,paymentSessionId:'3ds_fixture'},adapter);
 return {store,user,other,w,draft,details,data,adapter,calls,state,review,submit};
}
test('booking is gated without provider approval and live certification',async t=>{const f=fixture(t);await assert.rejects(createBookingReview(f.store,f.user.id,{kind:'book',detailsId:f.details.id},new DuffelBookingAdapter({env:{}})),/not configured/);assert.equal(new DuffelBookingAdapter({env:{DUFFEL_ACCESS_TOKEN:'test',DUFFEL_BOOKING_APPROVED:'true',DUFFEL_LIVE_ENABLED:'true'}}).authorized,false);});
test('protected booking details require every searched traveler and valid age',t=>{const f=fixture(t);for(const passengers of [[],[{...f.data.passengers[0],id:'invented'}],[{...f.data.passengers[0],bornOn:'2020-01-01'}],[{...f.data.passengers[0],bornOn:'1990-02-31'}]])assert.throws(()=>saveBookingDetails(f.store,f.user.id,f.w.conversation.id,{draftVersion:f.draft.version,details:{...f.data,passengers}}));});
test('transaction review is owner-scoped and requires its exact confirmation',async t=>{const f=fixture(t),r=await f.review();assert.throws(()=>submitBookingOperation(f.store,f.other.id,{reviewId:r.id,key:'cross'},f.adapter),/not found/);for(const patch of [{confirmed:false},{confirmationToken:'yes'},{paymentSessionId:'invented'}])assert.throws(()=>submitBookingOperation(f.store,f.user.id,{reviewId:r.id,key:'bad',confirmed:true,confirmationToken:r.confirmationToken,paymentSessionId:'3ds_fixture',...patch},f.adapter));assert.equal(f.calls.submit,0);});
test('review binds changed draft and passenger details',async t=>{const f=fixture(t),r=await f.review();f.store.put(f.user.id,'trip-draft',{...f.draft,constraints:{...f.draft.constraints,travelers:2}},{id:f.draft.id,expectedVersion:f.draft.version});assert.throws(()=>f.submit(r),/changed/);});
test('expired review cannot be confirmed',async t=>{const f=fixture(t),r=await f.review();f.store.put(f.user.id,'booking-review',{...r,expiresAt:Date.now()-1},{id:r.id,expectedVersion:r.version});assert.throws(()=>f.submit(r),/expired/);});
test('duplicate confirmations with different keys consume one review once',async t=>{const f=fixture(t),r=await f.review(),a=f.submit(r),b=submitBookingOperation(f.store,f.user.id,{reviewId:r.id,key:'different-key',confirmed:true,confirmationToken:r.confirmationToken,paymentSessionId:'3ds_fixture'},f.adapter);assert.equal(a.id,b.id);await runBookingOperation(f.store,f.user.id,a.id,f.adapter);await runBookingOperation(f.store,f.user.id,a.id,f.adapter);assert.equal(f.calls.submit,1);});
test('changed complete price requires a new review and never submits',async t=>{const f=fixture(t),op=f.submit(await f.review());f.state.amount++;const result=await runBookingOperation(f.store,f.user.id,op.id,f.adapter);assert.equal(result.state,'review-required');assert.equal(f.calls.submit,0);});
test('ambiguous submission is reconciled after restart without a second purchase',async t=>{const f=fixture(t),op=f.submit(await f.review());f.state.fail=true;f.state.issued=false;let result=await runBookingOperation(f.store,f.user.id,op.id,f.adapter);assert.equal(result.state,'reconciling');f.state.fail=false;f.state.issued=true;result=await runBookingOperation(f.store,f.user.id,op.id,f.adapter);assert.equal(result.state,'completed');assert.equal(f.calls.submit,1);assert.equal(f.calls.reconcile,1);assert.equal(f.store.list(f.user.id,'supplier-order').length,1);});
test('captured payment without a ticket stays in reconciliation',async t=>{const f=fixture(t);f.state.issued=false;const result=await runBookingOperation(f.store,f.user.id,f.submit(await f.review()).id,f.adapter);assert.equal(result.paymentState,'captured');assert.equal(result.ticketState,'not-issued');assert.equal(result.state,'reconciling');});
test('payment decline is separate from issuance',async t=>{const f=fixture(t);f.state.issued=false;f.state.decline=true;const result=await runBookingOperation(f.store,f.user.id,f.submit(await f.review()).id,f.adapter);assert.equal(result.state,'declined');assert.equal(result.ticketState,'not-issued');});
test('imported tickets never establish servicing authority',async t=>{const f=fixture(t);const ticket=f.store.put(f.user.id,'ticket',{confirmation:'USER-TYPED'});await assert.rejects(createBookingReview(f.store,f.user.id,{kind:'cancel',orderId:ticket.id},f.adapter),/not found/);const order=f.store.put(f.user.id,'supplier-order',{supplierReference:'ord_typed',servicingAuthority:false});await assert.rejects(createBookingReview(f.store,f.user.id,{kind:'refund',orderId:order.id},f.adapter),/authority/);});
test('supplier webhook verifies exact bytes, timestamp and signature',()=>{const raw=Buffer.from('{"hello":"world"}'),time=Math.floor(Date.now()/1000),secret='fixture-secret',sig=createHmac('sha256',secret).update(time+'.').update(raw).digest('hex'),header=`t=${time},v1=${sig}`;assert.doesNotThrow(()=>verifyDuffelWebhook(raw,header,secret));assert.throws(()=>verifyDuffelWebhook(Buffer.from('{}'),header,secret));assert.throws(()=>verifyDuffelWebhook(raw,header,secret,Date.now()+600000));assert.throws(()=>verifyDuffelWebhook(raw,header,undefined));});
test('duplicate signed events wake reconciliation once and never mutate issued state',async t=>{const f=fixture(t),op=f.submit(await f.review());const complete=await runBookingOperation(f.store,f.user.id,op.id,f.adapter);const raw=Buffer.from(JSON.stringify({id:'wev_fixture',type:'order.updated',live_mode:false,idempotency_key:'same-event',data:{object:{id:'ord_fixture',metadata:{wayline_operation:op.supplierKey}}}}));const time=Math.floor(Date.now()/1000),secret='fixture-secret',header=`t=${time},v1=${createHmac('sha256',secret).update(time+'.').update(raw).digest('hex')}`;assert.equal(receiveDuffelWebhook(f.store,raw,header,f.adapter,{secret}).matched,true);assert.equal(receiveDuffelWebhook(f.store,raw,header,f.adapter,{secret}).duplicate,true);assert.equal(f.store.get(f.user.id,complete.id,'booking-operation').state,'completed');assert.equal(f.store.list(f.user.id,'booking-event').length,1);});
test('checkout handoff permits only exact approved HTTPS hosts and never changes orders',()=>{assert.equal(approvedCheckoutUrl('https://checkout.example.com/pay',['checkout.example.com']),'https://checkout.example.com/pay');for(const url of ['javascript:alert(1)','https://evil.example/','https://checkout.example.com.evil.test/','https://user@checkout.example.com/pay','http://checkout.example.com'])assert.throws(()=>approvedCheckoutUrl(url,['checkout.example.com']));});

test('a second reviewed purchase cannot duplicate the same selected offer',async t=>{const f=fixture(t),a=await f.review(),b=await f.review();f.submit(a);assert.throws(()=>f.submit(b),/already exists/);assert.equal(f.calls.submit,0);});
test('servicing cannot cross supplier environments',async t=>{const f=fixture(t);const order=f.store.put(f.user.id,'supplier-order',{supplier:'other',live:false,supplierReference:'ord_fixture',servicingAuthority:true});await assert.rejects(createBookingReview(f.store,f.user.id,{kind:'cancel',orderId:order.id},f.adapter),/different supplier/);assert.equal(f.calls.quote,0);});
test('refreshing a completed purchase reads the supplier without resubmission',async t=>{const f=fixture(t);const op=await runBookingOperation(f.store,f.user.id,f.submit(await f.review()).id,f.adapter);await runBookingOperation(f.store,f.user.id,op.id,f.adapter,{refresh:true});assert.equal(f.calls.submit,1);assert.equal(f.calls.reconcile,1);const order=f.store.get(f.user.id,op.orderId,'supplier-order');assert.equal(order.paymentHistory.length,1);assert.equal(order.economics[0].previousSpending.amount,12345);});

test('submitted and uncertain operations retain reconciliation data without card or identity values',async t=>{
 const f=fixture(t),review=await f.review();f.state.fail=true;
 const op=await runBookingOperation(f.store,f.user.id,f.submit(review).id,f.adapter);
 assert.equal(op.state,'reconciling');assert.equal(op.paymentSessionId,null);assert.equal(op.reviewSnapshot.quote.supplierPayload.offerId,'off_fixture');assert.equal(op.reviewSnapshot.quote.charge.amount,12345);
 const stored=JSON.stringify([op,f.store.get(f.user.id,review.id,'booking-review')]);
 for(const secret of ['tcd_fixture','3ds_fixture','fixture@example.invalid','1990-01-01','+12025550123'])assert.ok(!stored.includes(secret),secret+' must be cleared');
 assert.throws(()=>f.store.get(f.user.id,f.details.id,'booking-details'),{status:404});
 assert.equal(f.submit(review).id,op.id);
 f.state.fail=false;assert.equal((await runBookingOperation(f.store,f.user.id,op.id,f.adapter)).state,'completed');assert.equal(f.calls.submit,1);assert.equal(f.calls.reconcile,1);
});
