import {stationGuide,cities} from '../catalog.mjs';
import {storeFlightObservation,historicalReliability} from '../shopping/providerContracts.mjs';
import {serviceIdentity} from '../shopping/connections.mjs';
export const travelKnowledge=[
 {id:'baggage',match:/luggage|baggage|bags?/i,title:'Baggage and complete fares',text:'Baggage allowances and prices depend on the airline and fare. Wayline checks the requested bags for every traveler and flight. An unknown required fee prevents a complete-price recommendation. Review the actual allowance, dimensions and fees before payment.',source:'US Department of Transportation · Buying a ticket',url:'https://www.transportation.gov/individuals/aviation-consumer-protection/buying-ticket',observedAt:'2026-09-12T00:00:00Z'},
 {id:'separate',match:/separate|connection|protected|guarantee|on time|reliab/i,title:'Connections and uncertainty',text:'Separate tickets can have separate conditions and change charges. Wayline displays the ticket groups and treats connection protection as unknown unless the supplier confirms it. Connection time and fewer transfers describe resilience; they do not guarantee arrival or establish historical reliability.',source:'Wayline connection and evidence policy',url:null,observedAt:'2026-09-12T00:00:00Z'},
 {id:'price',match:/price|cheapest|evidence|fee|cost/i,title:'What the lowest-price label covers',text:'Lowest complete price found refers only to the disclosed providers, airports, dates and returned offers. Required known charges are counted for the whole party. Unknown costs remain visible, and the payment review reprices the selected card and services before a purchase.',source:'Wayline search coverage and exact-review policy',url:null,observedAt:'2026-09-12T00:00:00Z'},
 {id:'capabilities',match:/.*/,title:'Travel questions and actions',text:'Ask about options, ticket conditions, baggage, connections, weather, boarding, bookings or saved travel details. I use the available records and provider evidence. Requests to spend money or service tickets open an exact review; personal and payment details use protected forms.',source:'Wayline traveler action registry',url:null,observedAt:'2026-09-12T00:00:00Z'}
];
export function knowledgeAnswer(input){const entry=travelKnowledge.find(k=>k.match.test(input));return {reply:entry.text,evidence:[{label:entry.title,value:entry.text,source:entry.source,url:entry.url,observedAt:entry.observedAt}]};}
export async function flightEvidence(store,userId,draft,travel){
 const selected=draft.selected?.flight;if(!selected)return {reply:'Select a flight itinerary to match exact flight identities before retrieving status.',evidence:[]};
 const provider=travel.flightStatusProvider;
 if(!provider?.license?.statusAllowed)return {reply:'Flight status and historical reliability require a licensed status provider with approved FlightAware access. No status is inferred from an offer.',evidence:[]};
 const rows=[];
 for(const service of selected.services.filter(s=>s.mode==='air')){try{const observation=await provider.status(service);storeFlightObservation(store,userId,serviceIdentity(service),observation,{license:provider.license});rows.push({label:service.operator+' '+service.serviceNumber,value:observation.status+(observation.gate?' · departure gate '+observation.gate:''),source:'FlightAware AeroAPI',url:observation.sourceUrl,observedAt:observation.observedAt});const cohort=historicalReliability(store.list(userId,'flight-observation').map(r=>r.observation),{origin:service.origin.iata,destination:service.destination.iata,operatingCarrierCode:service.operatingCarrierCode,serviceNumber:service.serviceNumber,departureHour:Number(new Intl.DateTimeFormat('en-US',{timeZone:service.origin.timezone,hour:'2-digit',hourCycle:'h23'}).format(new Date(service.departure))),timeZone:service.origin.timezone});if(cohort.available)rows.push({label:'Historical observed arrivals',value:`${cohort.onTimePercent}% within 15 minutes; ${cohort.sampleCount} observations, ${cohort.periodStart} to ${cohort.periodEnd}. ${cohort.limitation}`,source:'FlightAware licensed observations',url:observation.sourceUrl,observedAt:observation.observedAt});}catch(e){rows.push({label:service.operator+' '+service.serviceNumber,value:e.message,source:'Observation unavailable',observedAt:new Date().toISOString()});}}
 return {reply:'These observations match the selected service, airports and scheduled departure. Status can change; a forecast is not a guarantee.',evidence:rows};
}
export async function stationEvidence(draft,travel,input){
 const selected=draft.selected?.journey;const query=input.replace(/^(?:show|find|where|is)\s*/i,'').replace(/station|boarding|guidance|entrance|accessible|for|the|do i board at/gi,' ').trim();
 const sample=cities.find(c=>query.toLowerCase().includes(c.station.toLowerCase())||query.toLowerCase()===c.name.toLowerCase());
 if(sample||draft.constraints.mode==='sample'){const guide=stationGuide(sample?.id??selected?.fromId??draft.constraints.from);if(guide)return {reply:guide.directions.join(' '),evidence:guide.facilities.map(f=>({label:f.name,value:f.status,source:guide.source,observedAt:new Date().toISOString()}))};}
 const place=typeof draft.constraints.from==='object'?draft.constraints.from:null;
 const data=await travel.call('places',{q:query||place?.id||selected?.from||''});
 const exact=data.places.filter(p=>p.id===place?.id||p.name.toLowerCase()===query.toLowerCase());
 if(exact.length!==1)return {reply:'Choose the exact station or airport in trip requirements. Facilities, indoor paths and boarding gates must be verified for that location.',evidence:[]};
 return {reply:`${exact[0].name}: match the route and destination on the departure board and follow posted station signs. Indoor paths and facilities have not been verified.`,evidence:[{label:'Station location',value:`${exact[0].name}`,source:data.source,observedAt:data.fetchedAt}]};
}
