/** Curated discovery seed, NOT an assertion of live nationwide coverage. */
export const states = Object.entries({
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of Columbia",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
}).map(([code, name]) => ({ code, name }));
const seed = [
  ["AL", "Birmingham", "BJCTA"],
  ["AK", "Anchorage", "People Mover"],
  ["AZ", "Phoenix", "Valley Metro"],
  ["AR", "Little Rock", "Rock Region METRO"],
  ["CA", "Los Angeles", "LA Metro"],
  ["CA", "San Jose", "VTA"],
  ["CA", "San Francisco", "SFMTA"],
  ["CA", "Oakland", "BART"],
  ["CO", "Denver", "RTD"],
  ["CT", "Hartford", "CTtransit"],
  ["DE", "Wilmington", "DART First State"],
  ["DC", "Washington", "WMATA"],
  ["FL", "Miami", "Miami-Dade Transit"],
  ["GA", "Atlanta", "MARTA"],
  ["HI", "Honolulu", "TheBus"],
  ["ID", "Boise", "Valley Regional Transit"],
  ["IL", "Chicago", "CTA"],
  ["IL", "Chicago", "Metra"],
  ["IN", "Indianapolis", "IndyGo"],
  ["IA", "Des Moines", "DART"],
  ["KS", "Wichita", "Wichita Transit"],
  ["KY", "Louisville", "TARC"],
  ["LA", "New Orleans", "RTA"],
  ["ME", "Portland", "Greater Portland METRO"],
  ["MD", "Baltimore", "Maryland Transit Administration"],
  ["MA", "Boston", "MBTA"],
  ["MI", "Detroit", "DDOT"],
  ["MN", "Minneapolis", "Metro Transit"],
  ["MS", "Jackson", "JTRAN"],
  ["MO", "St. Louis", "Metro Transit"],
  ["MT", "Missoula", "Mountain Line"],
  ["NE", "Omaha", "Metro"],
  ["NV", "Las Vegas", "RTC Southern Nevada"],
  ["NH", "Manchester", "Manchester Transit Authority"],
  ["NJ", "Newark", "NJ TRANSIT"],
  ["NM", "Albuquerque", "ABQ RIDE"],
  ["NY", "New York", "MTA"],
  ["NC", "Charlotte", "CATS"],
  ["ND", "Fargo", "MATBUS"],
  ["OH", "Columbus", "COTA"],
  ["OK", "Oklahoma City", "EMBARK"],
  ["OR", "Portland", "TriMet"],
  ["PA", "Philadelphia", "SEPTA"],
  ["RI", "Providence", "RIPTA"],
  ["SC", "Charleston", "CARTA"],
  ["SD", "Sioux Falls", "Sioux Area Metro"],
  ["TN", "Nashville", "WeGo Public Transit"],
  ["TX", "Dallas", "DART"],
  ["UT", "Salt Lake City", "UTA"],
  ["VT", "Burlington", "Green Mountain Transit"],
  ["VA", "Richmond", "GRTC"],
  ["WA", "Seattle", "King County Metro"],
  ["WA", "Seattle", "Sound Transit"],
  ["WV", "Charleston", "Kanawha Valley Regional Transportation Authority"],
  ["WI", "Milwaukee", "MCTS"],
  ["WY", "Cheyenne", "Cheyenne Transit Program"],
  ["US", "National", "Amtrak"],
  ["US", "National", "Greyhound"],
  ["US", "National", "FlixBus"],
  ["US", "National", "OurBus"],
  ["US", "National", "Megabus"],
  ["US", "Northeast", "Peter Pan"],
];
export const agencies = seed.map(([state, city, name], i) => ({
  id: `agency-${i + 1}`,
  name,
  state,
  city,
  coverage: "discovery-seed",
  staticFeed: "unverified",
  vehiclePositions: name === "MBTA" ? "adapter available" : "not configured",
  tripUpdates: "not configured",
  alerts: name === "MBTA" ? "adapter available" : "not configured",
  ticketing: "provider required",
  fares: "unverified",
  accessibility: "unverified",
  crowding: "unverified",
  lastSuccess: null,
  source: name === "MBTA" ? "https://api-v3.mbta.com/" : null,
}));
export const cities = [
  ["la", "Los Angeles", "CA", 34.056, -118.236, "America/Los_Angeles", "Union Station"],
  ["sj", "San Jose", "CA", 37.33, -121.902, "America/Los_Angeles", "Diridon Station"],
  [
    "sf",
    "San Francisco",
    "CA",
    37.776,
    -122.395,
    "America/Los_Angeles",
    "Salesforce Transit Center",
  ],
  [
    "oak",
    "Oakland",
    "CA",
    37.804,
    -122.272,
    "America/Los_Angeles",
    "12th Street / Oakland City Center",
  ],
  ["bos", "Boston", "MA", 42.352, -71.055, "America/New_York", "South Station"],
  ["nyc", "New York", "NY", 40.751, -73.994, "America/New_York", "Moynihan Train Hall"],
  [
    "ind",
    "Indianapolis",
    "IN",
    39.765,
    -86.158,
    "America/Indiana/Indianapolis",
    "Julia M. Carson Transit Center",
  ],
  ["chi", "Chicago", "IL", 41.879, -87.64, "America/Chicago", "Union Station"],
  ["sea", "Seattle", "WA", 47.602, -122.339, "America/Los_Angeles", "Colman Dock"],
  [
    "bai",
    "Bainbridge Island",
    "WA",
    47.623,
    -122.511,
    "America/Los_Angeles",
    "Bainbridge Island Ferry Terminal",
  ],
  ["atl", "Atlanta", "GA", 33.753, -84.391, "America/New_York", "Five Points"],
  [
    "lax",
    "LAX Airport",
    "CA",
    33.943,
    -118.409,
    "America/Los_Angeles",
    "LAX / Metro Transit Center",
  ],
].map(([id, name, state, lat, lon, timezone, station]) => ({
  id,
  name,
  state,
  lat,
  lon,
  timezone,
  station,
}));
export const corridors = [
  { from: "la", to: "sj", minutes: 470, km: 550 },
  { from: "bos", to: "nyc", minutes: 260, km: 345 },
  { from: "ind", to: "chi", minutes: 210, km: 290 },
  { from: "sf", to: "oak", minutes: 37, km: 17 },
  { from: "sea", to: "bai", minutes: 48, km: 14 },
  { from: "la", to: "lax", minutes: 85, km: 29 },
];
export const operatorLinks = {
  Amtrak: "https://www.amtrak.com/",
  Greyhound: "https://www.greyhound.com/",
  FlixBus: "https://www.flixbus.com/",
  "LA Metro": "https://www.metro.net/",
  VTA: "https://www.vta.org/",
  MBTA: "https://www.mbta.com/",
  BART: "https://www.bart.gov/",
  "Washington State Ferries": "https://wsdot.wa.gov/travel/washington-state-ferries",
  OurBus: "https://www.ourbus.com/",
  Megabus: "https://us.megabus.com/",
  "Peter Pan": "https://peterpanbus.com/",
};
export const defaultPreferences = {
  priority: "balanced",
  budgetCents: 8500,
  maxTransfers: 3,
  maxWalkMinutes: 25,
  minConnectionMinutes: 8,
  walkSpeed: 1.2,
  wheelchair: false,
  stepFree: false,
  avoidStairs: false,
  elevatorRequired: false,
  lowFloor: false,
  transferAssistance: false,
  serviceAnimal: false,
  visualAnnouncements: false,
  audioNavigation: false,
  lessCrowded: false,
  preferTrain: false,
  avoidBus: false,
  nightWalking: true,
  coveredTransfers: false,
  riskTolerance: "balanced",
  importance: "normal",
  language: "en",
  visitor: false,
  notifyCritical: true,
  notifyInfo: false,
  // Whether a push notification (see server/push.mjs) shows the real alert title/body, or a
  // generic phrase. Push can surface on a locked screen, a materially wider exposure than the
  // in-app alert list, so this defaults off even though notifyCritical/notifyInfo are on.
  pushDetails: false,
  quietStart: "22:00",
  quietEnd: "07:00",
  historyDays: 90,
  saveHistory: true,
  shareLocation: false,
  autoRecovery: false,
  recoveryLimitCents: 1000,
  emergencyMinutes: 45,
};
export function discoverAgencies(from, to) {
  const names = new Set(
    [from, to].filter(Boolean).map((id) => cities.find((c) => c.id === id)?.name),
  );
  return agencies.filter((a) => names.has(a.city) || a.state === "US");
}
export function stationGuide(cityId) {
  const city = cities.find((c) => c.id === cityId);
  if (!city) return null;
  return {
    id: city.id,
    name: city.station,
    city: city.name,
    lat: city.lat,
    lon: city.lon,
    source: "sample guide — verify signs with station staff",
    official: false,
    facilities: [
      { name: "Accessible entrance", status: "Verify on arrival" },
      { name: "Elevator", status: "Status unknown" },
      { name: "Restrooms", status: "Check station signs" },
      { name: "Waiting area", status: "Hours unverified" },
      { name: "Food & water", status: "Availability unverified" },
      { name: "Charging / Wi-Fi", status: "Availability unverified" },
      { name: "Ticket desk", status: "Check operator hours" },
      { name: "Baggage storage", status: "Provider dependent" },
      { name: "Rideshare pickup", status: "Follow local signs" },
    ],
    directions: [
      "Find the station’s posted departure board.",
      "Match the operator, service number and destination on your ticket.",
      "Use the signed accessible path if you need step-free access.",
      "Confirm the boarding area with station staff before proceeding.",
    ],
    parking: { rateCents: null, availability: "unknown", evChargers: "not connected" },
  };
}
