import { DatabaseSync } from 'node:sqlite';
import { randomBytes, randomUUID, createCipheriv, createDecipheriv, createHmac, createHash, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { mkdirSync, readFileSync, writeFileSync, chmodSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { DomainError } from './domain/journeys.mjs';
const derive=promisify(scrypt);
export const hashToken=v=>createHash('sha256').update(v).digest('hex');
export class Store {
 constructor({directory=process.env.DATA_DIR||resolve('data'),key=process.env.DATA_ENCRYPTION_KEY,production=process.env.NODE_ENV==='production'}={}){
  mkdirSync(directory,{recursive:true,mode:0o700});
  if(!key){if(production)throw new Error('DATA_ENCRYPTION_KEY is required in production.');const path=join(directory,'.encryption-key');if(!existsSync(path))writeFileSync(path,randomBytes(32).toString('hex'),{mode:0o600,flag:'wx'});key=readFileSync(path,'utf8').trim();}
  if(!/^[a-f\d]{64}$/i.test(key))throw new Error('DATA_ENCRYPTION_KEY must contain 64 hexadecimal characters.');this.key=Buffer.from(key,'hex');
  this.db=new DatabaseSync(join(directory,'wayline.sqlite'));chmodSync(join(directory,'wayline.sqlite'),0o600);
  this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
   CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL) STRICT;
   CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email_hash TEXT UNIQUE,password_hash TEXT,profile TEXT NOT NULL,created_at INTEGER NOT NULL) STRICT;
   CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,csrf TEXT NOT NULL,expires_at INTEGER NOT NULL) STRICT;
   CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
   CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);
   CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind TEXT NOT NULL,payload TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,expires_at INTEGER) STRICT;
   CREATE INDEX IF NOT EXISTS idx_records_user_kind_time ON records(user_id,kind,updated_at DESC);
   CREATE INDEX IF NOT EXISTS idx_records_expiry ON records(expires_at) WHERE expires_at IS NOT NULL;
   CREATE TABLE IF NOT EXISTS shares(id TEXT PRIMARY KEY,token_hash TEXT UNIQUE NOT NULL,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,journey_id TEXT NOT NULL REFERENCES records(id) ON DELETE CASCADE,scopes TEXT NOT NULL,expires_at INTEGER NOT NULL) STRICT;
   CREATE INDEX IF NOT EXISTS idx_shares_user ON shares(user_id);
   CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,user_id TEXT,action TEXT NOT NULL,resource_id TEXT,at INTEGER NOT NULL) STRICT;
   CREATE INDEX IF NOT EXISTS idx_audit_user_time ON audit(user_id,at DESC);
   INSERT OR IGNORE INTO schema_version VALUES(1,datetime('now')); PRAGMA optimize;`);
 }
 encrypt(value){const iv=randomBytes(12);const c=createCipheriv('aes-256-gcm',this.key,iv);const encrypted=Buffer.concat([c.update(JSON.stringify(value),'utf8'),c.final()]);return [iv,c.getAuthTag(),encrypted].map(b=>b.toString('base64url')).join('.');}
 decrypt(value){const [iv,tag,data]=value.split('.').map(s=>Buffer.from(s,'base64url'));const c=createDecipheriv('aes-256-gcm',this.key,iv);c.setAuthTag(tag);return JSON.parse(Buffer.concat([c.update(data),c.final()]).toString('utf8'));}
 transaction(fn){this.db.exec('BEGIN IMMEDIATE');try{const result=fn();this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 emailHash(email){return createHmac('sha256',this.key).update(email.trim().toLowerCase()).digest('hex');}
 user(id){const u=this.db.prepare('SELECT * FROM users WHERE id=?').get(id);return u?{id:u.id,registered:Boolean(u.email_hash),...this.decrypt(u.profile)}:null;}
 createGuest(){const id=randomUUID();this.db.prepare('INSERT INTO users(id,profile,created_at) VALUES(?,?,?)').run(id,this.encrypt({name:'Traveler',email:null,preferences:{},role:'traveler'}),Date.now());return this.user(id);}
 updateUser(id,patch){const u=this.user(id);if(!u)throw new DomainError('Account not found.',404);delete u.registered;delete u.id;this.db.prepare('UPDATE users SET profile=? WHERE id=?').run(this.encrypt({...u,...patch}),id);this.audit(id,'PROFILE_UPDATED',id);return this.user(id);}
 async register(id,{name,email,password}){validateCredentials(email,password);if(typeof name!=='string'||!name.trim()||name.length>100)throw new DomainError('Enter a name of up to 100 characters.');if(this.user(id)?.registered)throw new DomainError('This session already has an account.',409);const salt=randomBytes(16).toString('hex');const result=await derive(password,salt,64,{N:16384,r:8,p:1});const hash=`${salt}:${result.toString('hex')}`;try{this.transaction(()=>{this.db.prepare('UPDATE users SET email_hash=?,password_hash=? WHERE id=?').run(this.emailHash(email),hash,id);this.updateUser(id,{name:name.trim(),email:email.trim().toLowerCase(),role:'traveler'});this.audit(id,'ACCOUNT_REGISTERED',id);});}catch(e){if(String(e.code).includes('SQLITE_CONSTRAINT'))throw new DomainError('An account with this email already exists.',409);throw e;}return this.user(id);}
 async login(email,password){validateCredentials(email,password,false);const row=this.db.prepare('SELECT id,password_hash FROM users WHERE email_hash=?').get(this.emailHash(email));const [salt,expected]=(row?.password_hash??'00000000000000000000000000000000:'+Buffer.alloc(64).toString('hex')).split(':');const actual=await derive(password,salt,64,{N:16384,r:8,p:1});if(!row||!timingSafeEqual(Buffer.from(expected,'hex'),actual))throw new DomainError('Email or password is incorrect.',401);this.audit(row.id,'SIGNED_IN',row.id);return this.user(row.id);}
 session(userId){const token=randomBytes(32).toString('base64url'),csrf=randomBytes(24).toString('base64url');const days=Math.max(1,Math.min(30,Number(process.env.SESSION_DAYS)||14));this.db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(hashToken(token),userId,csrf,Date.now()+days*86400000);return {token,csrf,userId};}
 findSession(token){if(!token)return null;return this.db.prepare('SELECT user_id AS userId,csrf,expires_at FROM sessions WHERE token_hash=? AND expires_at>?').get(hashToken(token),Date.now())??null;}
 logout(token){this.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(token));}
 list(userId,kind){return this.db.prepare('SELECT * FROM records WHERE user_id=? AND kind=? AND (expires_at IS NULL OR expires_at>?) ORDER BY updated_at DESC LIMIT 1000').all(userId,kind,Date.now()).map(row=>this.decode(row));}
 decode(row){return {...this.decrypt(row.payload),id:row.id,version:row.version,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()};}
 get(userId,id,kind){const row=this.db.prepare('SELECT * FROM records WHERE user_id=? AND id=? AND (expires_at IS NULL OR expires_at>?)').get(userId,id,Date.now());if(!row||(kind&&row.kind!==kind))throw new DomainError('Record not found.',404,'NOT_FOUND');return this.decode(row);}
 put(userId,kind,value,{id=randomUUID(),expectedVersion,expiresAt}={}){const existing=this.db.prepare('SELECT user_id,version,kind,expires_at FROM records WHERE id=?').get(id);if(existing&&(existing.user_id!==userId||existing.kind!==kind))throw new DomainError('Record not found.',404);if(existing&&(expectedVersion===undefined||existing.version!==expectedVersion))throw new DomainError('This item changed in another tab. Refresh and try again.',409,'VERSION_CONFLICT');if(this.db.prepare('SELECT count(*) AS n FROM records WHERE user_id=?').get(userId).n>=3000&&!existing)throw new DomainError('Account storage limit reached. Export and remove old items.',429);const now=Date.now();const expiration=expiresAt===undefined?(existing?.expires_at??null):expiresAt;const payload={...value};delete payload.id;delete payload.version;delete payload.createdAt;delete payload.updatedAt;if(existing){this.db.prepare('UPDATE records SET payload=?,version=version+1,updated_at=?,expires_at=? WHERE id=? AND user_id=?').run(this.encrypt(payload),now,expiration,id,userId);}else{this.db.prepare('INSERT INTO records VALUES(?,?,?,?,1,?,?,?)').run(id,userId,kind,this.encrypt(payload),now,now,expiration);}this.audit(userId,`${kind.toUpperCase()}_${existing?'UPDATED':'CREATED'}`,id);return this.get(userId,id,kind);}
 remove(userId,id){this.get(userId,id);this.db.prepare('DELETE FROM records WHERE id=? AND user_id=?').run(id,userId);this.audit(userId,'RECORD_DELETED',id);}
 audit(userId,action,resourceId=null){this.db.prepare('INSERT INTO audit VALUES(?,?,?,?,?)').run(randomUUID(),userId,action,resourceId,Date.now());}
 audits(userId){return this.db.prepare('SELECT action,resource_id AS resourceId,at FROM audit WHERE user_id=? ORDER BY at DESC LIMIT 100').all(userId);}
 share(userId,journeyId,{hours=24,location=false}={}){this.get(userId,journeyId,'journey');if(!Number.isInteger(hours)||hours<1||hours>168)throw new DomainError('Share expiry must be 1–168 hours.');const token=randomBytes(32).toString('base64url'),id=randomUUID(),expiresAt=Date.now()+hours*3600000;this.db.prepare('INSERT INTO shares VALUES(?,?,?,?,?,?)').run(id,hashToken(token),userId,journeyId,JSON.stringify({location:Boolean(location)}),expiresAt);this.audit(userId,'SHARE_CREATED',journeyId);return {id,token,expiresAt};}
 shares(userId){return this.db.prepare('SELECT id,journey_id AS journeyId,expires_at AS expiresAt,scopes FROM shares WHERE user_id=? AND expires_at>?').all(userId,Date.now()).map(s=>({...s,scopes:JSON.parse(s.scopes)}));}
 revokeShare(userId,id){const result=this.db.prepare('DELETE FROM shares WHERE user_id=? AND id=?').run(userId,id);if(!result.changes)throw new DomainError('Share not found.',404);this.audit(userId,'SHARE_REVOKED',id);}
 shared(token){const s=this.db.prepare('SELECT * FROM shares WHERE token_hash=? AND expires_at>?').get(hashToken(token),Date.now());if(!s)throw new DomainError('This sharing link has expired or was revoked.',404);const j=this.get(s.user_id,s.journey_id,'journey');const location=JSON.parse(s.scopes).location;return {from:j.from,to:j.to,departure:j.departure,arrival:j.arrival,state:j.state,dataMode:j.dataMode,updatedAt:j.updatedAt,expiresAt:s.expires_at,location:location?j.legs.filter(l=>l.tracking?.source==='live-gps').map(l=>({operator:l.operator,position:l.tracking.position,observedAt:l.tracking.observedAt})):undefined};}
 export(userId){const rows=this.db.prepare('SELECT * FROM records WHERE user_id=? ORDER BY created_at').all(userId);return {exportedAt:new Date().toISOString(),profile:this.user(userId),records:rows.map(r=>({kind:r.kind,...this.decode(r)})),audit:this.audits(userId)};}
 deleteHistory(userId){this.transaction(()=>{this.db.prepare("DELETE FROM records WHERE user_id=? AND kind IN ('journey','ticket','claim','alert','agent','report','search','recovery','idempotency')").run(userId);this.audit(userId,'HISTORY_DELETED');});}
 deleteAccount(userId){this.transaction(()=>{this.db.prepare('DELETE FROM users WHERE id=?').run(userId);this.db.prepare('DELETE FROM audit WHERE user_id=?').run(userId);});}
 cleanup(now=Date.now()){this.db.prepare('DELETE FROM sessions WHERE expires_at<=?').run(now);this.db.prepare('DELETE FROM shares WHERE expires_at<=?').run(now);this.db.prepare('DELETE FROM records WHERE expires_at IS NOT NULL AND expires_at<=?').run(now);this.db.prepare('DELETE FROM audit WHERE at<?').run(now-90*86400000);this.db.prepare('DELETE FROM users WHERE email_hash IS NULL AND created_at<? AND NOT EXISTS(SELECT 1 FROM sessions WHERE sessions.user_id=users.id)').run(now-14*86400000);}
 close(){this.db.close();}
}
function validateCredentials(email,password,registration=true){if(typeof email!=='string'||email.length>254||!/^\S+@\S+\.\S+$/.test(email))throw new DomainError('Enter a valid email address.');if(typeof password!=='string'||password.length>128||password.length<(registration?12:1))throw new DomainError('Use a password between 12 and 128 characters.');}
