import { initialTrips, stations, dateLabel, type Trip, type StationCode } from './model';
import type { ChatMessage } from './Assistant';
export function makeDraft():Trip {return {...initialTrips[0],id:'WL-'+crypto.randomUUID().slice(0,8).toUpperCase(),date:'2026-10-02',disrupted:false,alternative:null,status:'upcoming'};}
export function replyFor(text:string,trip:Trip,automatic:boolean):ChatMessage {
const normalized=text.toLowerCase();const selected=`${stations[trip.from].city} to ${stations[trip.to].city}`;let reply:ChatMessage;
if(/cancel/.test(normalized))reply={role:'assistant',text:trip.status==='cancelled'?'This sample journey is already cancelled. You can restore a snapshot in Journey protection.':`I can cancel your ${selected} trip on ${dateLabel(trip.date)}. Review the cancellation below; your current plan will be saved first.`,action:trip.status==='cancelled'?'backups':'cancel'};
else if(/backup|alternativ|delay|disrupt|protect/.test(normalized))reply={role:'assistant',text:`Your ${selected} journey has express, regional rail and coach alternatives. Automatic demo recovery is ${automatic?'on':'off'}. Open your options to compare them or simulate a disruption.`,action:'backups'};
else if(/pdf|ticket|download/.test(normalized))reply={role:'assistant',text:'Your PDF includes departure and arrival details, the complete itinerary, traveler count, illustrative fare and backup plans. It is clearly labeled as a sample travel document.',action:'pdf'};
else if(/map|direction|station/.test(normalized))reply={role:'assistant',text:`Explore the real map between ${stations[trip.from].name} and ${stations[trip.to].name}. Click either station for directions, zoom in, or tilt the map.`,action:'map'};
else if(/chang|edit|move|reschedul/.test(normalized)){const draft={...trip};const date=text.match(/\b\d{4}-\d{2}-\d{2}\b/);const time=text.match(/\b([01]\d|2[0-3]):[0-5]\d\b/);if(date)draft.date=date[0];if(time)draft.departure=time[0];reply={role:'assistant',text:trip.status==='cancelled'?'This journey is cancelled. Restore it before changing its details.':`Let’s update your ${selected} journey.${date||time?' I have filled in the date or time you mentioned.':''} Review the details and save when you’re ready.`,action:trip.status==='cancelled'?'backups':'edit',draft};}
else if(/add|new|plan|book|trip|travel/.test(normalized)){const draft=makeDraft();const matches=Object.entries(stations).map(([code,s])=>({code:code as StationCode,index:normalized.indexOf(s.city.toLowerCase().replace(', d.c.',''))})).filter(m=>m.index>=0).sort((a,b)=>a.index-b.index);if(matches.length>=2){draft.from=matches[0].code;draft.to=matches[1].code;}else if(matches.length===1){draft.to=matches[0].code;if(draft.from===draft.to)draft.from='WAS';}const date=text.match(/\b\d{4}-\d{2}-\d{2}\b/);if(date)draft.date=date[0];const time=text.match(/\b([01]\d|2[0-3]):[0-5]\d\b/);if(time)draft.departure=time[0];reply={role:'assistant',text:`I’ve prepared a sample trip from ${stations[draft.from].city} to ${stations[draft.to].city}. Set the date, time and traveler details before adding it.`,action:'add',draft};}
else reply={role:'assistant',text:'This guided prototype supports adding, changing and cancelling sample trips, backup options, maps and PDF itineraries. Try “Change my trip to 2026-09-20 at 11:00”, or choose one of the actions below.'};
return {...reply,tripId:trip.id};
}
