import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Icon } from '../components/ui';
import { initialTrips, stations, dateLabel, loadDemo, storageKey, withTrips, type Trip } from './model';
import { downloadItinerary } from './pdf';
import { makeDraft, replyFor } from './chat';
import { Action, Modal, TripEditor, Itinerary } from './ui';
import { Backups, TicketPage, MapPage } from './Views';
import Overview from './Overview';
import Assistant, {type ChatMessage} from './Assistant';
import './style.css';
type Page='Journeys'|'Assistant'|'Tickets'|'Map explorer'|'Backups';
type ModalState={type:'add'|'edit'|'cancel'|'itinerary';trip:Trip}|null;
const navItems:[Page,string][]=[['Journeys','route'],['Assistant','spark'],['Tickets','ticket'],['Map explorer','globe']];
const pageHash:Record<Page,string>={Journeys:'journeys',Assistant:'assistant',Tickets:'tickets','Map explorer':'map',Backups:'backups'};
function routePage():Page{return (Object.keys(pageHash) as Page[]).find(p=>pageHash[p]===location.hash.slice(1))||'Journeys';}
const greeting:ChatMessage={role:'assistant',text:'Hello. Let’s get the details taken care of. I can add a journey, change your plans, prepare a cancellation, or find your backup options. Which would you like to try?'};
function Prototype(){
const [state,setState]=useState(loadDemo),[page,setPage]=useState<Page>(routePage),[selectedId,setSelectedId]=useState(()=>state.trips.find(t=>t.status==='upcoming')?.id||state.trips[0]?.id||''),[filter,setFilter]=useState<'upcoming'|'cancelled'>('upcoming'),[modal,setModal]=useState<ModalState>(null),[toast,setToast]=useState(''),[savingError,setSavingError]=useState(false),[chat,setChat]=useState<ChatMessage[]>([greeting]);
const trip=state.trips.find(t=>t.id===selectedId)||state.trips[0]||initialTrips[0];
useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(state));setSavingError(false);}catch{setSavingError(true);}},[state]);
useEffect(()=>{const changed=()=>setPage(routePage());window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed);},[]);
useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[toast]);
function go(next:Page){setPage(next);location.hash=pageHash[next];window.scrollTo({top:0,behavior:'instant'});}
function contextGo(next:Page,t:Trip){setSelectedId(t.id);go(next);}
function edit(target:Trip=trip){setSelectedId(target.id);setModal({type:'edit',trip:target});}
function openAdd(draft?:Trip){setModal({type:'add',trip:draft?{...draft,id:makeDraft().id}:makeDraft()});}
function saveTrip(saved:Trip){const isNew=modal?.type==='add';setState(s=>withTrips(s,isNew?[saved,...s.trips]:s.trips.map(t=>t.id===saved.id?saved:t),`${isNew?'Added':'Changed'} journey to ${stations[saved.to].city}.`));setSelectedId(saved.id);setFilter('upcoming');setModal(null);setToast(isNew?'Trip added. Three backup options are ready.':'Trip updated. Your previous plan is saved.');if(page==='Assistant')setChat(c=>[...c,{role:'assistant',text:`Done. Your ${stations[saved.from].city} to ${stations[saved.to].city} trip is set for ${dateLabel(saved.date)} at ${saved.departure}. Its itinerary and backup options are ready.`}]);}
function cancelTrip(target:Trip){setState(s=>withTrips(s,s.trips.map(t=>t.id===target.id?{...t,status:'cancelled'}:t),`Cancelled sample trip to ${stations[target.to].city}.`));setModal(null);setToast('Sample trip cancelled. Restore it from Journey protection anytime.');if(page==='Assistant')setChat(c=>[...c,{role:'assistant',text:'Your sample trip has been cancelled. Its earlier version is saved in Journey protection. No operator booking or payment was affected.'}]);}
function download(target:Trip){downloadItinerary(target);setToast('Your two-page sample itinerary PDF is ready.');}
function chatAction(message:ChatMessage){const target=state.trips.find(t=>t.id===message.tripId);if(message.action==='add'){openAdd(message.draft);return;}if(!target){setToast('This journey changed. Select a journey and ask again.');return;}setSelectedId(target.id);if(message.action==='edit'){if(target.status==='cancelled'){go('Backups');return;}edit({...target,date:message.draft?.date||target.date,departure:message.draft?.departure||target.departure});}else if(message.action==='cancel'){if(target.status==='cancelled'){setToast('This sample journey is already cancelled.');return;}setModal({type:'cancel',trip:target});}else if(message.action==='backups')go('Backups');else if(message.action==='pdf')download(target);else if(message.action==='map')go('Map explorer');}
function send(text:string){if(!text.trim())return;setChat(c=>[...c,{role:'user',text:text.trim()},replyFor(text,trip,state.automatic)]);}
const toggle=()=>setState(s=>({...s,automatic:!s.automatic}));
const selector=<label className="wl-trip-select"><span>YOUR JOURNEY</span><select aria-label="Select journey" value={trip.id} onChange={e=>setSelectedId(e.target.value)}>{state.trips.map(t=><option key={t.id} value={t.id}>{stations[t.from].city} → {stations[t.to].city} · {dateLabel(t.date)}{t.status==='cancelled'?' · Cancelled':''}</option>)}</select></label>;
const headings={Backups:['JOURNEY PROTECTION','Ready for the unexpected','Alternative routes and a recoverable history of your plans.'],Tickets:['YOUR TRAVEL DOCUMENTS','Every detail. Ready to go','A complete itinerary, designed to travel with you.'],'Map explorer':['THE BIGGER PICTURE','Get to know your journey','Real geography. Station details. A better sense of where you’re going.']};
return <div className="wl-app"><aside className="wl-sidebar"><a className="wl-brand" href="/prototype.html"><span className="wl-brand-symbol">w</span>wayline<span className="wl-brand-period">.</span></a><span className="wl-eyebrow wl-nav-label">YOUR WORKSPACE</span><nav aria-label="Main navigation">{navItems.map(([name,icon])=><button key={name} className={page===name?'active':''} aria-current={page===name?'page':undefined} onClick={()=>go(name)}><Icon name={icon}/><span>{name}</span>{name==='Assistant'&&<span className="wl-nav-tag">NEW</span>}</button>)}</nav><div className="wl-sidebar-bottom"><div className="wl-guardian-note"><Icon name="shield" size={24}/><strong>A plan for the unexpected.</strong><p>Backup routes, always within reach.</p><button onClick={()=>go('Backups')}>Journey protection <Icon name="arrow" size={16}/></button></div><div className="wl-profile"><span className="wl-avatar">V</span><div><strong>My workspace</strong><small>Personal travel</small></div></div></div></aside><div className="wl-workspace"><header className="wl-topbar"><div><span className="wl-top-section">Workspace</span><span className="wl-slash">/</span><strong>{page==='Backups'?'Journey protection':page}</strong></div><div className="wl-top-actions"><span className="wl-prototype-tag">DESIGN PREVIEW</span><span className="wl-top-meta">Sample journeys · local only</span><span className="wl-avatar small">V</span></div></header><main className={`wl-content ${page==='Assistant'?'wl-chat-content':''}`}>
{page==='Journeys'&&<Overview state={state} selectedId={selectedId} select={setSelectedId} filter={filter} setFilter={setFilter} add={()=>openAdd()} edit={edit} cancel={t=>setModal({type:'cancel',trip:t})} download={download} itinerary={t=>{setSelectedId(t.id);setModal({type:'itinerary',trip:t});}} backups={t=>contextGo('Backups',t)} assistant={t=>contextGo('Assistant',t)} toggle={toggle} savingError={savingError}/>}
{page==='Assistant'&&<Assistant state={state} trip={trip} chat={chat} send={send} act={chatAction} reset={()=>setChat([greeting])} selector={selector} backups={()=>go('Backups')} toggle={toggle} itinerary={()=>setModal({type:'itinerary',trip})}/>}
{page!=='Journeys'&&page!=='Assistant'&&<><div className="wl-heading"><div><p className="wl-eyebrow">{headings[page][0]}</p><h1>{headings[page][1]}<span>.</span></h1><p className="wl-subtitle">{headings[page][2]}</p></div>{page==='Tickets'?<Action primary icon="download" onClick={()=>download(trip)}>Download PDF</Action>:<Action icon={page==='Backups'?'arrow':'shield'} onClick={()=>go(page==='Backups'?'Journeys':'Backups')}>{page==='Backups'?'Your journeys':'Backup routes'}</Action>}</div>{selector}{page==='Backups'?<Backups state={state} trip={trip} update={setState} notify={setToast}/>:page==='Tickets'?<TicketPage trip={trip} download={()=>download(trip)} assistant={()=>go('Assistant')}/>:<MapPage trip={trip} tickets={()=>go('Tickets')}/>}</>}
{savingError&&<div role="alert" className="wl-storage-warning">Your browser could not save this demo. Keep this tab open or download your itinerary PDF.</div>}<footer className="wl-footer"><span>WAYLINE / TRAVEL, CONSIDERED.</span><span>Prototype · schedules and fares are illustrative</span></footer></main></div>
{modal&&<Modal title={modal.type==='add'?'A new journey.':modal.type==='edit'?'A change of plans.':modal.type==='cancel'?'Cancel this sample trip?':'Your complete itinerary'} onClose={()=>setModal(null)}>{modal.type==='add'||modal.type==='edit'?<TripEditor key={modal.trip.id+modal.type} trip={modal.trip} isNew={modal.type==='add'} onSave={saveTrip} onClose={()=>setModal(null)}/>:modal.type==='cancel'?<div className="wl-cancel-content"><span className="wl-cancel-icon"><Icon name="ticket" size={28}/></span><h3>{stations[modal.trip.from].city} → {stations[modal.trip.to].city}</h3><p>{dateLabel(modal.trip.date,true)} · {modal.trip.departure}</p><div className="wl-form-note"><Icon name="shield" size={21}/><span>The trip will move to Cancelled. A snapshot will let you restore it. No real booking or refund is involved.</span></div><div className="wl-modal-actions"><Action onClick={()=>setModal(null)}>Keep my trip</Action><Action className="danger" onClick={()=>cancelTrip(modal.trip)}>Cancel sample trip</Action></div></div>:<div className="wl-modal-itinerary"><Itinerary trip={modal.trip}/><div className="wl-modal-actions"><Action icon="calendar" disabled={modal.trip.status==='cancelled'} onClick={()=>setModal({type:'edit',trip:modal.trip})}>Change trip</Action><Action primary icon="download" onClick={()=>download(modal.trip)}>Download PDF</Action></div></div>}</Modal>}
{toast&&<div className="wl-toast" role="status"><Icon name="check" size={18}/><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><Icon name="close" size={16}/></button></div>}
</div>;}
createRoot(document.getElementById('root')!).render(<Prototype/>);

