import ProviderCheckoutForm from './ProviderCheckoutForm';
import {lazy,Suspense,useEffect,useState} from 'react';
const SupplierCardForm=lazy(()=>import('./SupplierCardForm'));
import {api} from '../api';
import {BookingReviewDetails,type BookingReview as Review} from './BookingReviewDetails';
import type {WorkspaceSnapshot,FlightMoney} from '../workspaceTypes';
import {Button,Field,Notice} from './ui';
type Passenger={id:string;givenName:string;familyName:string;bornOn:string;title:'mr'|'ms'|'mrs'|'miss'|'dr';gender:'m'|'f';email:string;phone:string};

type Operation={id:string;state:string;paymentState:string;ticketState:string;manualHelpRequired?:boolean};
const price=(m:FlightMoney)=>new Intl.NumberFormat(undefined,{style:'currency',currency:m.currency}).format(m.amount/10**m.scale);
export default function BookingConversationForm({workspace,kind='book'}:{workspace:WorkspaceSnapshot;kind?:'book'|'cancel'|'exchange'|'refund'}) {
 const [capabilities,setCapabilities]=useState<{live:boolean;authorized:boolean;checkout:boolean;capabilities:Record<string,boolean>}|null>(null);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[clientKey,setClientKey]=useState(''),[cardId,setCardId]=useState('');
 const [review,setReview]=useState<Review|null>(null),[operation,setOperation]=useState<Operation|null>(null),[approved,setApproved]=useState(false);
 const [orders,setOrders]=useState<{id:string;supplierReference:string;ticketState:string}[]>([]),[orderId,setOrderId]=useState('');
 const [passengers,setPassengers]=useState<Passenger[]>(()=> (workspace.draft.constraints.passengers??[]).map(p=>({id:p.id,givenName:'',familyName:'',bornOn:'',title:'ms',gender:'f',email:'',phone:''})));
 const [sections,setSections]=useState<{id:string;services:{operator:string;serviceNumber:string;origin:{name:string};destination:{name:string};departure:string}[]}[]>([]),[sliceId,setSliceId]=useState(''),[changeDate,setChangeDate]=useState('');
 const [changeSearch,setChangeSearch]=useState<{id:string;offers:{id:string;changeAmount:string;currency:string;slices:typeof sections}[]}|null>(null),[changeOfferId,setChangeOfferId]=useState('');
 const [availableServices,setAvailableServices]=useState<{id:string;type:string;maximum_quantity:number;price:FlightMoney;passenger_ids:string[];segment_ids:string[];metadata?:{type?:string}}[]>([]),[services,setServices]=useState<{id:string;quantity:number}[]>([]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void api<typeof capabilities>('/shopping/booking/capabilities').then(setCapabilities).catch(e=>setError(e.message));void api<{operations:Operation[];reviews:Review[]}>('/shopping/booking/current?conversationId='+encodeURIComponent(workspace.conversation.id)).then(data=>{const active=data.operations.find(o=>['queued','submitting','reconciling'].includes(o.state));if(active)setOperation(active);else{const pending=data.reviews.find(r=>r.kind===kind);if(pending){setReview(pending);setOrderId(pending.source.orderId??'');setCardId(pending.source.details?.cardId??pending.source.changeCardId??'');if(pending.source.details?.passengers)setPassengers(pending.source.details.passengers);setApproved(false);}}}).catch(e=>setError(e.message));if(kind!=='book')void api<typeof orders>('/shopping/orders').then(setOrders).catch(e=>setError(e.message));},[kind,workspace.conversation.id]);
 const operationId=operation?.id,operationState=operation?.state;
 useEffect(()=>{if(!operationId||!operationState||!['queued','submitting','reconciling'].includes(operationState))return;const timer=setInterval(()=>void api<Operation>(`/shopping/operations/${operationId}`).then(setOperation).catch(e=>setError(e.message)),3000);return()=>clearInterval(timer);},[operationId,operationState]);
 const edit=(id:string,key:keyof Passenger,value:string)=>{setReview(null);setApproved(false);setPassengers(list=>list.map(p=>p.id===id?{...p,[key]:value}:p));};
 const secureCard=(!clientKey?<Button disabled={busy} onClick={()=>void run(async()=>{const key=await api<{component_client_key:string}>('/shopping/booking/card-key','POST',{conversationId:workspace.conversation.id,orderId:orderId||undefined});setClientKey(key.component_client_key);})}>Open secure card form</Button>:<Suspense fallback={<p role="status">Loading secure card form…</p>}><SupplierCardForm clientKey={clientKey} busy={busy} onPrepared={id=>{setCardId(id);setReview(null);setApproved(false);}} onError={setError}/></Suspense>);
 return <section className="booking-conversation"><h3>{kind==='book'?'Review and book tickets':`Review ticket ${kind}`}</h3>{error&&<Notice tone="error">{error}</Notice>}
 {!capabilities?<p role="status">Checking supplier access…</p>:!capabilities.capabilities[kind]?<><Notice>Approved in-app provider access for this operation is unavailable. Imported tickets and saved plans are separate from supplier bookings.</Notice>{kind==='book'&&<ProviderCheckoutForm workspace={workspace} available={capabilities.checkout}/>}</>:<>
 <Notice>{capabilities.live?'Authorized live supplier workflow':'Supplier test environment — no real tickets'}</Notice>
 {operation?<div role="status"><p>Operation: {operation.state}</p><p>Payment: {operation.paymentState}</p><p>Tickets: {operation.ticketState}</p>{operation.manualHelpRequired&&<Notice>Supplier reconciliation needs attention. Do not repeat the purchase.</Notice>}</div>:<>
 {kind==='book'?<form onSubmit={e=>{e.preventDefault();void run(async()=>{const details=await api<{id:string}>('/shopping/booking/details','POST',{conversationId:workspace.conversation.id,draftVersion:workspace.draft.version,details:{passengers,services,paymentMethod:'card',cardId}});setReview(await api<Review>('/shopping/booking/reviews','POST',{kind,detailsId:details.id}));setApproved(false);});}}>
 <p>Enter names exactly as shown on travel identification. These values are sent to the protected booking endpoint and supplier, never to Llama.</p>
 {passengers.map((p,i)=><fieldset key={p.id} disabled={busy}><legend>Traveler {i+1}</legend>{(['givenName','familyName','bornOn','email','phone'] as const).map(key=><Field key={key} label={{givenName:'Given name',familyName:'Family name',bornOn:'Date of birth',email:'Email',phone:'Phone with country code'}[key]}><input required type={key==='bornOn'?'date':key==='email'?'email':key==='phone'?'tel':'text'} value={p[key]} onChange={e=>edit(p.id,key,e.target.value)}/></Field>)}<Field label="Title"><select value={p.title} onChange={e=>edit(p.id,'title',e.target.value)}>{['mr','ms','mrs','miss','dr'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Supplier passenger gender field"><select value={p.gender} onChange={e=>edit(p.id,'gender',e.target.value)}><option value="f">Female</option><option value="m">Male</option></select></Field></fieldset>)}
<fieldset><legend>Baggage and additional services</legend><Button disabled={busy} onClick={()=>void run(async()=>{setAvailableServices(await api<typeof availableServices>('/shopping/booking/services?conversationId='+encodeURIComponent(workspace.conversation.id)));})}>Load supplier services</Button>{availableServices.map(s=><Field key={s.id} label={s.type+' · '+price(s.price)+' each · '+(s.metadata?.type??'supplier service')}><input type="number" min="0" max={s.maximum_quantity} value={services.find(v=>v.id===s.id)?.quantity??0} onChange={e=>{const quantity=Number(e.target.value);setServices(current=>[...current.filter(v=>v.id!==s.id),...(quantity>0?[{id:s.id,quantity}]:[])]);setReview(null);setApproved(false);}}/><small>{s.passenger_ids.length} traveler(s), {s.segment_ids.length} flight(s) covered.</small></Field>)}<p>The exact review reprices these selections and the payment card together.</p></fieldset> {secureCard}
 <Button type="submit" disabled={busy||!cardId}>Get exact booking review</Button>
 </form>:<div><Field label="Supplier order"><select value={orderId} onChange={e=>{const id=e.target.value;setOrderId(id);setReview(null);setApproved(false);setSliceId('');setSections([]);setChangeSearch(null);setChangeOfferId('');if(kind==='exchange'&&id)void run(async()=>setSections(await api<typeof sections>('/shopping/booking/order-sections?orderId='+encodeURIComponent(id))));}}><option value="">Choose an issued order</option>{orders.map(o=><option key={o.id} value={o.id}>{o.supplierReference} · {o.ticketState}</option>)}</select></Field>{kind==='exchange'&&orderId&&<fieldset><legend>Change a flight section</legend><Field label="Flight section"><select value={sliceId} onChange={e=>{setSliceId(e.target.value);setReview(null);setApproved(false);setChangeSearch(null);setChangeOfferId('');}}><option value="">Choose the section to replace</option>{sections.map(s=><option key={s.id} value={s.id}>{s.services.map(l=>l.operator+' '+l.serviceNumber).join(', ')} · {new Date(s.services[0].departure).toLocaleString()}</option>)}</select></Field><Field label="New departure date"><input type="date" value={changeDate} onChange={e=>{setChangeDate(e.target.value);setReview(null);setApproved(false);setChangeSearch(null);setChangeOfferId('');}}/></Field><Button disabled={busy||!sliceId||!changeDate} onClick={()=>void run(async()=>{setChangeSearch(await api<typeof changeSearch>('/shopping/booking/change-options','POST',{orderId,change:{sliceId,departureDate:changeDate}}));})}>Find change offers</Button>{changeSearch&&<><p>{changeSearch.offers.length} change offers. Review the complete replacement before confirming.</p>{changeSearch.offers.map(o=><label className="booking-change-option" key={o.id}><input type="radio" name="change-offer" value={o.id} checked={changeOfferId===o.id} onChange={()=>{setChangeOfferId(o.id);setReview(null);setApproved(false);}}/>{o.changeAmount} {o.currency} change amount {o.slices.flatMap(s=>s.services).map((l,i)=><span key={i}>{l.operator} {l.serviceNumber}: {l.origin.name} to {l.destination.name} · {new Date(l.departure).toLocaleString()}</span>)}</label>)}</>}{secureCard}</fieldset>}<Button disabled={!orderId||busy||(kind==='exchange'&&!changeOfferId)} onClick={()=>void run(async()=>{setReview(await api<Review>('/shopping/booking/reviews','POST',{kind,orderId,changeSearchId:changeSearch?.id,changeOfferId,changeCardId:cardId||undefined}));setApproved(false);})}>Get fresh servicing review</Button></div>}
 {review&&<section className="workspace-flight-review"><h4>Exact transaction review</h4><BookingReviewDetails review={review}/><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> I reviewed this itinerary, travelers, amount, currency and terms.</label><Button kind="primary" disabled={busy||!approved||review.expiresAt<=Date.now()} onClick={()=>void run(async()=>{let paymentSessionId:string|undefined;if(review.quote.paymentAuthenticationRequired){let key=clientKey;if(!key){const result=await api<{component_client_key:string}>('/shopping/booking/card-key','POST',{conversationId:workspace.conversation.id,orderId:orderId||undefined});key=result.component_client_key;setClientKey(key);}const {createThreeDSecureSession}=await import('@duffel/components');const session=await createThreeDSecureSession(key,cardId,review.quote.id,review.source.details?.services??[],true);if(session.status!=='ready_for_payment'||session.resource_id!==review.quote.id||session.live_mode!==review.quote.live)throw Error('Supplier authentication is not ready for this exact review.');paymentSessionId=session.id;}setOperation(await api<Operation>('/shopping/operations','POST',{reviewId:review.id,confirmationToken:review.confirmationToken,confirmed:true,key:review.id,paymentSessionId}));})}>Confirm {kind==='book'?`purchase ${price(review.quote.charge)}`:kind+' request'}</Button></section>}
 </>}
 </>}
 </section>;
}
