import {useEffect,useState} from 'react';
import {api,localInput} from '../api';
import type {WorkspaceSnapshot,FlightCandidate,FlightMoney} from '../workspaceTypes';
import {Button,Field,Notice} from './ui';
type Service={id:string;mode?:string;operator:string;serviceNumber?:string;origin:{name:string};destination:{name:string};departure:string;arrival:string};
type Order={id:string;version:number;conversationId:string;bookingReference?:string;supplierReference:string;itinerary:{services:Service[]};searchRequest?:{currency:string}};
type Recovery={id:string;notice:string;completedServices:Service[];search:{state:string;reason?:string};options:{candidate:FlightCandidate;planningEligible:boolean;cashRequiredNow:FlightMoney|null;previousSpending:FlightMoney|null;refundsReceived:FlightMoney|null;refundsPending:FlightMoney|null}[]};
const money=(m:FlightMoney|null)=>m?new Intl.NumberFormat(undefined,{style:'currency',currency:m.currency}).format(m.amount/10**m.scale):'Not verified';
export default function SupplierRecoveryForm({workspace,onConversation}:{workspace:WorkspaceSnapshot;onConversation?:(id:string)=>void}) {
 const [orders,setOrders]=useState<Order[]>([]),[orderId,setOrderId]=useState(''),[completed,setCompleted]=useState(0),[target,setTarget]=useState(0),[ready,setReady]=useState(localInput(new Date(Date.now()+3600000))),[cap,setCap]=useState(''),[confirmed,setConfirmed]=useState(false);
 const [recovery,setRecovery]=useState<Recovery|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const order=orders.find(o=>o.id===orderId);
 useEffect(()=>{let active=true;void api<Order[]>('/shopping/orders').then(rows=>{if(!active)return;const own=rows.filter(o=>o.conversationId===workspace.conversation.id).map(o=>({...o,itinerary:{services:o.itinerary.services.filter(s=>s.mode==='air')}})).filter(o=>o.itinerary.services.length);setOrders(own);if(own.length===1){setOrderId(own[0].id);setTarget(own[0].itinerary.services.length-1);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[workspace.conversation.id]);
 useEffect(()=>{if(!recovery||!['queued','partial'].includes(recovery.search.state))return;let active=true;const timer=setTimeout(()=>{void api<Recovery>('/shopping/recoveries/'+recovery.id).then(r=>{if(active)setRecovery(r);}).catch(e=>{if(active)setError(e.message);});},3000);return()=>{active=false;clearTimeout(timer);};},[recovery]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section aria-label="Supplier recovery"><h4>Find a replacement from your reached airport</h4>{error&&<Notice tone="error">{error}</Notice>}
 {!orders.length&&<Notice>No supplier order is linked to this conversation. Imported tickets and saved comparisons do not establish an issued booking.</Notice>}
 <form onSubmit={e=>{e.preventDefault();if(!order)return;void run(async()=>{if(cap&&!/^\d+(\.\d{1,2})?$/.test(cap))throw Error('Enter an extra-cash amount with at most two decimal places.');const r=await api<{id:string}>('/shopping/orders/'+order.id+'/recovery','POST',{orderVersion:order.version,completedCount:completed,destinationIndex:target,readyAt:new Date(ready).toISOString(),confirmedPosition:confirmed,cashCap:cap?{amount:Math.round(Number(cap)*100),currency:order.searchRequest?.currency??'USD',scale:2}:null});setRecovery(await api<Recovery>('/shopping/recoveries/'+r.id));});}}>
 <Field label="Affected supplier booking"><select required value={orderId} onChange={e=>{setOrderId(e.target.value);setCompleted(0);setConfirmed(false);setRecovery(null);setTarget((orders.find(o=>o.id===e.target.value)?.itinerary.services.filter(s=>s.mode==='air').length??1)-1);}}><option value="">Choose a booking</option>{orders.map(o=><option key={o.id} value={o.id}>{o.bookingReference??o.supplierReference}</option>)}</select></Field>
 {order&&<><Field label="Your reached airport"><select value={completed} onChange={e=>{const n=Number(e.target.value);setCompleted(n);setTarget(v=>Math.max(v,n));setConfirmed(false);setRecovery(null);}}>{order.itinerary.services.map((s,i)=><option key={s.id} value={i}>{i===0?'Before the first flight: '+s.origin.name:'After completing '+i+' flight(s): '+order.itinerary.services[i-1].destination.name}</option>)}</select></Field>
 <Field label="Replace travel up to"><select value={target} onChange={e=>{setTarget(Number(e.target.value));setRecovery(null);}}>{order.itinerary.services.map((s,i)=>i>=completed?<option key={s.id} value={i}>{s.destination.name} after {s.operator} {s.serviceNumber}</option>:null)}</select></Field></>}
 <Field label="Earliest boarding-ready time (device time zone)"><input required type="datetime-local" value={ready} onChange={e=>{setReady(e.target.value);setConfirmed(false);setRecovery(null);}}/></Field>
 <Field label={'Extra cash available ('+(order?.searchRequest?.currency??'USD')+')'}><input inputMode="decimal" value={cap} onChange={e=>{setCap(e.target.value);setRecovery(null);}} placeholder="No additional limit"/></Field>
 <label><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I confirm my reached airport, completed flights, and earliest time I can finish airport procedures and be ready to board.</label>
 <Button type="submit" disabled={busy||!order||!confirmed}>Verify status and find replacements</Button></form>
 {recovery&&<><Notice>{recovery.notice}</Notice><p role="status">Replacement search: {recovery.search.state} {recovery.search.reason??''}</p><p>Completed flights preserved: {recovery.completedServices.length}</p>
 {recovery.options.map(o=><section key={o.candidate.id}><h5>{o.candidate.services.map(s=>s.origin.name+' to '+s.destination.name).join(' · ')}</h5><p>{new Date(o.candidate.services[0].departure).toLocaleString()} · {o.candidate.durationMinutes} minutes</p><dl><dt>Complete replacement price</dt><dd>{money(o.cashRequiredNow)}</dd><dt>Previous spending</dt><dd>{money(o.previousSpending)}</dd><dt>Refunds received</dt><dd>{money(o.refundsReceived)}</dd><dt>Refunds pending</dt><dd>{money(o.refundsPending)}</dd></dl>{o.candidate.limitation&&<Notice>{o.candidate.limitation}</Notice>}{o.candidate.pricing.unknownComponents.length>0&&<Notice>A protected card quote is required to calculate the full price before purchase review.</Notice>}<Button disabled={busy||!o.planningEligible} onClick={()=>void run(async()=>{const w=await api<WorkspaceSnapshot>('/shopping/recoveries/'+recovery.id+'/draft','POST',{candidateId:o.candidate.id});onConversation?.(w.conversation.id);})}>Open replacement draft for review</Button></section>)}
 {!recovery.options.length&&['complete','partial-failure','failed','blocked'].includes(recovery.search.state)&&<p>No eligible replacement is available. Your original booking is retained.</p>}</>}
 </section>;
}
