import {checkSupplierMonitor} from '../server/shopping/supplierMonitoring.mjs';
import assert from 'node:assert/strict';
import {serviceIdentity} from '../server/shopping/connections.mjs';
import {normalizeDuffelOffer,withCardPaymentUncertainty} from '../server/shopping/duffel.mjs';
import {runShoppingQuery} from '../server/shopping/service.mjs';
import {runBookingOperation} from '../server/shopping/booking.mjs';
export const fixtureFlightStatus={license:{id:'fixture-license',statusAllowed:true,rawRetentionDays:1},status:async s=>({provider:'flightaware-aeroapi',serviceIdentity:serviceIdentity(s),flightId:'fixture-'+s.id,origin:s.origin.iata,destination:s.destination.iata,scheduledDeparture:s.departure,scheduledArrival:s.arrival,observedAt:new Date().toISOString(),status:Date.parse(s.arrival)<Date.now()?'arrived':'cancelled',actualDeparture:Date.parse(s.arrival)<Date.now()?s.departure:null,actualArrival:Date.parse(s.arrival)<Date.now()?s.arrival:null,gate:null,sourceUrl:'https://www.flightaware.com/live/flight/FIXTURE'})};
export async function recoveryAndCancellationJourney(f,j,chat) {
 const now=Date.now(),id=f.w.conversation.id,booked=await f.book();
 let order=f.store.get(f.user.id,booked.orderId,'supplier-order');
 const first={...order.itinerary.services[0],departure:new Date(now-3*3600000).toISOString(),arrival:new Date(now-2*3600000).toISOString()};
 const second={...first,id:'seg_remaining',origin:first.destination,destination:{...first.destination,id:'arp_LAX',iata:'LAX',name:'Los Angeles',timezone:'America/Los_Angeles'},departure:new Date(now+3*3600000).toISOString(),arrival:new Date(now+6*3600000).toISOString()};
 order=f.store.put(f.user.id,'supplier-order',{...order,itinerary:{...order.itinerary,services:[first,second]}},{id:order.id,expectedVersion:order.version});
 const original=JSON.stringify(order);
 await chat(f,id,'Show my travel alert settings','manage_notifications',j);
 const monitor=await f.call('monitors',{orderId:order.id,orderVersion:order.version,enabled:true,consent:true});assert.equal(monitor.status,200);
 await checkSupplierMonitor(f.store,{userId:f.user.id,monitorId:monitor.value.id},fixtureFlightStatus);
 assert.ok(f.store.list(f.user.id,'alert').some(a=>a.kind==='supplier-status'&&a.title.includes('cancelled')));
 assert.equal((await f.call('monitors',{orderId:order.id,orderVersion:order.version,enabled:false})).value.state,'paused');
 let w=await chat(f,id,'Prepare a backup route for this disruption','prepare_recovery',j);
 assert.equal(w.messages.at(-1).protectedPanel,'prepare_recovery');
 const result=await f.call('orders/'+order.id+'/recovery',{orderVersion:order.version,completedCount:1,destinationIndex:1,readyAt:new Date(now+3600000).toISOString(),confirmedPosition:true,cashCap:{amount:15000,currency:'USD',scale:2}});
 assert.equal(result.status,201,JSON.stringify(result.value));assert.equal(result.value.completedServices[0].id,first.id);
 const search=f.store.get(f.user.id,result.value.searchId,'shopping-search'),raw=structuredClone(f.raw);
 raw.id='off_recovery';const segment=raw.slices[0].segments[0];segment.id='seg_recovery';segment.origin={...segment.origin,id:'arp_JFK',iata_code:'JFK',name:'JFK'};segment.destination={...segment.destination,id:'arp_LAX',iata_code:'LAX',name:'Los Angeles',time_zone:'America/Los_Angeles'};segment.departing_at=new Date(now+2*3600000).toISOString();segment.arriving_at=new Date(now+5*3600000).toISOString();
 const offer=withCardPaymentUncertainty(normalizeDuffelOffer(raw,search.request,{pas_fixture:'adult-1'}));
 await runShoppingQuery(f.store,{call:async()=>({offers:[offer],fetchedAt:new Date().toISOString()})},{userId:f.user.id,searchId:search.id,index:0});
 const view=await f.call('recoveries/'+result.value.id);assert.equal(view.status,200);
 assert.equal(view.value.options[0].cashRequiredNow,null);assert.equal(view.value.options[0].previousSpending.amount,10215);
 assert.equal(view.value.options[0].planningEligible,true);
 const draft=await f.call('recoveries/'+result.value.id+'/draft',{candidateId:offer.id});assert.equal(draft.status,201,JSON.stringify(draft.value));
 const reloaded=(await f.call('/api/conversations/'+draft.value.conversation.id)).value;
 assert.equal(reloaded.draft.selected.flight.id,offer.id);assert.equal(reloaded.conversation.recoveryId,result.value.id);
 assert.equal(JSON.stringify(f.store.get(f.user.id,order.id,'supplier-order')),original);
 w=await chat(f,id,'Cancel my booked ticket','cancel_ticket',j);assert.equal(w.messages.at(-1).protectedPanel,'cancel_ticket');
 const review=await f.review({kind:'cancel',orderId:order.id});assert.equal(f.state.confirmed,false);
 const operation=await f.submit(review);assert.equal((await f.submit(review)).id,operation.id);
 const outcome=await runBookingOperation(f.store,f.user.id,operation.id,f.adapter);
 assert.equal(outcome.ticketState,'cancelled');assert.equal(outcome.paymentState,'refund-pending');
 w=await chat(f,id,'Show my booking status','order_status',j);assert.ok(w.messages.at(-1).workflowEvidence.some(e=>e.value.includes('cancelled')));
 assert.equal(f.state.submitted,1);
}
